name: Gated-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libssl1.1 (for Ubuntu 24.04)
      run: |
        sudo apt-get update
        wget http://old-releases.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb || true
        sudo apt-get install -f -y  # Fix missing dependencies

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore **/AppInsights.EnterpriseTelemetry.sln
    - name: Build
      run: dotnet build **/AppInsights.EnterpriseTelemetry.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test **/AppInsights.EnterpriseTelemetry.sln --no-restore --verbosity normal
