# This workflow will publish the AppInsights.Telemetry package to https://nuget.org

name: Nuget-publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore **/AppInsights.EnterpriseTelemetry.sln
    - name: Build
      run: dotnet build **/AppInsights.EnterpriseTelemetry.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test **/AppInsights.EnterpriseTelemetry.sln --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack **/AppInsights.EnterpriseTelemetry.csproj
    - name: Publish
      run: dotnet publish **/*.nupkg --api-key oy2nmvjm6ioh6mg73f6amujwsabw755uxpsexv4nx5fyea --source https://api.nuget.org/v3/index.json
